/* 
 * File:   mcal_internal_interrupt.h
 * Author: yossef
 *
 * Created on April 5, 2023, 10:53 AM
 */

#ifndef MCAL_INTERNAL_INTERRUPT_H
#define	MCAL_INTERNAL_INTERRUPT_H

/*----------includes------------*/
#include "../mcal_interrupt_cfg.h"
/*--------------Macros---------------*/

/*--------function-Macro--------------*/
/*ADC-SECTION*/

#if ADC_INTERRUPT_FEATURE == INTERRUPT_FEATURE_ENABLE
#define ADC_INTERRUPT_ENABLE()      (PIE1bits.ADIE = INTERRUPT_FEATURE_ENABLE)
#define ADC_INTERRUPT_DISABLE()     (PIE1bits.ADIE = INTERRUPT_FEATURE_DISABLE)

#define ADC_INTERRUPT_CLEAR_FLAG()            (PIR1bits.ADIF = 0)
#if INTERRUPT_PRIORITY_LEVELS == INTERRUPT_FEATURE_ENABLE

#define ADC_INTERRUPT_PRI_HIGH()    (IPR1bits.ADIP = INTERRUPT_HIGH_PRI)
#define ADC_INTERRUPT_PRI_LOW()     (IPR1bits.ADIP = INTERRUPT_LOW_PRI)

#endif
#endif

#if TIMER0_INTERRUPT_FEATURE == INTERRUPT_FEATURE_ENABLE

#define TIMER0_INTERRUPT_ENABLE()      (INTCONbits.TMR0IE = 1)
#define TIMER0_INTERRUPT_DISABLE()     (INTCONbits.TMR0IE = 0)
#define TIMER0_INTERRUPT_CLEAR_FLAG()  (INTCONbits.TMR0IF = 0)

#if INTERRUPT_PRIORITY_LEVELS == INTERRUPT_FEATURE_ENABLE

#define TIMER0_INTERRUPT_PRI_HIGH()    (INTCON2bits.TMR0IP = 1)
#define TIMER0_INTERRUPT_PRI_LOW()     (INTCON2bits.TMR0IP = 0)

#endif

#endif


#if TIMER1_INTERRUPT_FEATURE == INTERRUPT_FEATURE_ENABLE

#define TIMER1_INTERRUPT_ENABLE()      (PIE1bits.TMR1IE = 1)
#define TIMER1_INTERRUPT_DISABLE()     (PIE1bits.TMR1IE = 0)
#define TIMER1_INTERRUPT_CLEAR_FLAG()  (PIR1bits.TMR1IF = 0)

#if INTERRUPT_PRIORITY_LEVELS == INTERRUPT_FEATURE_ENABLE

#define TIMER1_INTERRUPT_PRI_HIGH()    (IPR1bits.TMR1IP = 1)
#define TIMER1_INTERRUPT_PRI_LOW()     (IPR1bits.TMR1IP = 0)

#endif

#endif

#if TIMER2_INTERRUPT_FEATURE == INTERRUPT_FEATURE_ENABLE

#define TIMER2_INTERRUPT_ENABLE()       (PIE1bits.TMR2IE = 1)
#define TIMER2_INTERRUPT_DISABLE()      (PIE1bits.TMR2IE = 0)
#define TIMER2_INTERRUPT_CLEAR_FLAG()   (PIR1bits.TMR2IF = 0)

#if INTERRUPT_PRIORITY_LEVELS == INTERRUPT_FEATURE_ENABLE

#define TIMER2_INTERRUPT_PRI_HIGH()     (IPR1bits.TMR2IP = 1)
#define TIMER2_INTERRUPT_PRI_LOW()      (IPR1bits.TMR2IP = 0)

#endif
#endif

#if TIMER3_INTERRUPT_FEATURE == INTERRUPT_FEATURE_ENABLE

#define TIMER3_INTERRUPT_ENABLE()       (PIE2bits.TMR3IE = 1)
#define TIMER3_INTERRUPT_DISABLE()      (PIE2bits.TMR3IE = 0)
#define TIMER3_INTERRUPT_CLEAR_FLAG()   (PIR2bits.TMR3IF = 0)

#if INTERRUPT_PRIORITY_LEVELS == INTERRUPT_FEATURE_ENABLE

#define TIMER3_INTERRUPT_PRI_HIGH()     (IPR2bits.TMR3IP = 1)
#define TIMER3_INTERRUPT_PRI_LOW()      (IPR2bits.TMR3IP = 0)

#endif
#endif



#if CCP1_INTERRUPT_FEATURE == INTERRUPT_FEATURE_ENABLE

#define CCP1_INTERRUPT_ENABLE()       (PIE1bits.CCP1IE = 1)
#define CCP1_INTERRUPT_DISABLE()      (PIE1bits.CCP1IE = 0)
#define CCP1_INTERRUPT_CLEAR_FLAG()   (PIR1bits.CCP1IF = 0)

#if INTERRUPT_PRIORITY_LEVELS == INTERRUPT_FEATURE_ENABLE

#define CCP1_INTERRUPT_PRI_HIGH()     (IPR1bits.CCP1IP = 1)
#define CCP1_INTERRUPT_PRI_LOW()      (IPR1bits.CCP1IP = 0)

#endif
#endif

#if CCP2_INTERRUPT_FEATURE == INTERRUPT_FEATURE_ENABLE

#define CCP2_INTERRUPT_ENABLE()       (PIE2bits.CCP2IE = 1)
#define CCP2_INTERRUPT_DISABLE()      (PIE2bits.CCP2IE = 0)
#define CCP2_INTERRUPT_CLEAR_FLAG()   (PIR2bits.CCP2IF = 0)

#if INTERRUPT_PRIORITY_LEVELS == INTERRUPT_FEATURE_ENABLE

#define CCP2_INTERRUPT_PRI_HIGH()     (IPR2bits.CCP2IP = 1)
#define CCP2_INTERRUPT_PRI_LOW()      (IPR2bits.CCP2IP = 0)

#endif
#endif



// eusart
#define EUSART_TX_INTERRUPT_ENABLE()            (PIE1bits.TXIE = 1)
#define EUSART_TX_INTERRUPT_DISABLE()           (PIE1bits.TXIE = 0)





#define EUSART_RX_INTERRUPT_ENABLE()            (PIE1bits.RCIE = 1)
#define EUSART_RX_INTERRUPT_DISABLE()           (PIE1bits.RCIE = 0)


#if SPI_INTERRUPT_FEATURE == INTERRUPT_FEATURE_ENABLE

#define SPI_INTERRUPT_DISABLE()                 (PIE1bits.SSPIE = 0)
#define SPI_INTERRUPT_ENABLE()                  (PIE1bits.SSPIE = 1)
#define SPI_INTERRUPT_CLEAR_FLAG()              (PIR1bits.SSPIF = 0)

#if INTERRUPT_PRIORITY_LEVELS == INTERRUPT_FEATURE_ENABLE

#define SPI_INTERRUPT_PRI_SELECT()              (IPR1bits.SSPIP = SPI_INTERRUPT_PRI)

#endif
#endif

#if I2C_MSSP_INTERRUPT_FEATURE == INTERRUPT_FEATURE_ENABLE

#define I2C_MSSP_INTERRUPT_DISABLE()                 (PIE1bits.SSPIE = 0)
#define I2C_MSSP_INTERRUPT_ENABLE()                  (PIE1bits.SSPIE = 1)
#define I2C_MSSP_INTERRUPT_CLEAR_FLAG()              (PIR1bits.SSPIF = 0)

#if INTERRUPT_PRIORITY_LEVELS == INTERRUPT_FEATURE_ENABLE

#define I2C_MSSP_INTERRUPT_PRI_SELECT()              (IPR1bits.SSPIP = I2C_MSSP_INTERRUPT_PRI)

#endif
#endif

#if I2C_BUS_COLLISION_INTERRUPT_FEATURE == INTERRUPT_FEATURE_ENABLE

#define I2C_BUS_COLLISION_INTERRUPT_DISABLE()                 (PIE2bits.BCLIE = 0)
#define I2C_BUS_COLLISION_INTERRUPT_ENABLE()                  (PIE2bits.BCLIE = 1)
#define I2C_BUS_COLLISION_INTERRUPT_CLEAR_FLAG()              (PIR2bits.BCLIF = 0)

#if INTERRUPT_PRIORITY_LEVELS == INTERRUPT_FEATURE_ENABLE

#define I2C_BUS_COLLISION_INTERRUPT_PRI_SELECT()              (IPR2bits.BCLIP = I2C_BUS_COLLISION_INTERRUPT_PRI)

#endif
#endif

/*------------------*/

/*----------user-datatypes------------*/

/*------------interfaces-prototype-----*/

#endif

/* MCAL_INTERNAL_INTERRUPT_H */

